package com.west.forum.model.schema;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHEMA.USERTABLE.ID
     *
     * @mbg.generated Fri Nov 15 22:28:56 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHEMA.USERTABLE.ACCOUNT_ID
     *
     * @mbg.generated Fri Nov 15 22:28:56 CST 2019
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHEMA.USERTABLE.NAME
     *
     * @mbg.generated Fri Nov 15 22:28:56 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHEMA.USERTABLE.TOKEN
     *
     * @mbg.generated Fri Nov 15 22:28:56 CST 2019
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHEMA.USERTABLE.GMT_CREATE
     *
     * @mbg.generated Fri Nov 15 22:28:56 CST 2019
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHEMA.USERTABLE.GMT_MODIFIED
     *
     * @mbg.generated Fri Nov 15 22:28:56 CST 2019
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHEMA.USERTABLE.AVATAR_URL
     *
     * @mbg.generated Fri Nov 15 22:28:56 CST 2019
     */
    private String avatarUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHEMA.USERTABLE.ID
     *
     * @return the value of SCHEMA.USERTABLE.ID
     *
     * @mbg.generated Fri Nov 15 22:28:56 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHEMA.USERTABLE.ID
     *
     * @param id the value for SCHEMA.USERTABLE.ID
     *
     * @mbg.generated Fri Nov 15 22:28:56 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHEMA.USERTABLE.ACCOUNT_ID
     *
     * @return the value of SCHEMA.USERTABLE.ACCOUNT_ID
     *
     * @mbg.generated Fri Nov 15 22:28:56 CST 2019
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHEMA.USERTABLE.ACCOUNT_ID
     *
     * @param accountId the value for SCHEMA.USERTABLE.ACCOUNT_ID
     *
     * @mbg.generated Fri Nov 15 22:28:56 CST 2019
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHEMA.USERTABLE.NAME
     *
     * @return the value of SCHEMA.USERTABLE.NAME
     *
     * @mbg.generated Fri Nov 15 22:28:56 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHEMA.USERTABLE.NAME
     *
     * @param name the value for SCHEMA.USERTABLE.NAME
     *
     * @mbg.generated Fri Nov 15 22:28:56 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHEMA.USERTABLE.TOKEN
     *
     * @return the value of SCHEMA.USERTABLE.TOKEN
     *
     * @mbg.generated Fri Nov 15 22:28:56 CST 2019
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHEMA.USERTABLE.TOKEN
     *
     * @param token the value for SCHEMA.USERTABLE.TOKEN
     *
     * @mbg.generated Fri Nov 15 22:28:56 CST 2019
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHEMA.USERTABLE.GMT_CREATE
     *
     * @return the value of SCHEMA.USERTABLE.GMT_CREATE
     *
     * @mbg.generated Fri Nov 15 22:28:56 CST 2019
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHEMA.USERTABLE.GMT_CREATE
     *
     * @param gmtCreate the value for SCHEMA.USERTABLE.GMT_CREATE
     *
     * @mbg.generated Fri Nov 15 22:28:56 CST 2019
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHEMA.USERTABLE.GMT_MODIFIED
     *
     * @return the value of SCHEMA.USERTABLE.GMT_MODIFIED
     *
     * @mbg.generated Fri Nov 15 22:28:56 CST 2019
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHEMA.USERTABLE.GMT_MODIFIED
     *
     * @param gmtModified the value for SCHEMA.USERTABLE.GMT_MODIFIED
     *
     * @mbg.generated Fri Nov 15 22:28:56 CST 2019
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHEMA.USERTABLE.AVATAR_URL
     *
     * @return the value of SCHEMA.USERTABLE.AVATAR_URL
     *
     * @mbg.generated Fri Nov 15 22:28:56 CST 2019
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHEMA.USERTABLE.AVATAR_URL
     *
     * @param avatarUrl the value for SCHEMA.USERTABLE.AVATAR_URL
     *
     * @mbg.generated Fri Nov 15 22:28:56 CST 2019
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }
}